# criar um novo modulo

    :: 
    
        $ puppet module generate jads-dev --skip-interview


        :: Criando um manifesto:

            $ cd /etc/puppet/code/environments/production/modules/dev/manifests
            $ nano hosts

            :: Onde “dev” é o nome do módulo, e “hosts” o nome do manifesto.

                class edithosts::hosts {
    
                    ### maquina server ###
                    host { 'teste1.fcn.edu.br':
                        ip      => '10.10.10.01',
                        comment => 'Adicionado via Puppet'
                    }

                    host { 'teste2.fcn.edu.br':
                        ip      => '10.10.10.02',
                        comment => 'Adicionado via Puppet'
                    }
                }

            :: Verifique se tem algum erro no manifesto.

                $ puppet parser validate hosts.pp

    
    - A definição do node (node são os clientes rodando o puppet client, são seus hosts no geral).

        $ cd /etc/puppet/code/environments/production/manifests
        $ nano site.pp

            node 
                'puppetclient-01.devopslab.com.br',
                'puppetclient-02.devopslab.com.br',
                'puppetclient-03.devopslab.com.br',
                'puppetclient-04.devopslab.com.br'
                ## assim por diante.
            {
                include edithosts::hosts
            }

        :: Valide a configuração site.pp no intuito de achar erros.

            $ puppet parser validate site.pp
            $ puppet agent -t

            $ cat /etc/hosts
            # HEADER: This file was autogenerated at 2018-05-22 14:10:54 +0000
            # HEADER: by puppet.  While it can still be managed manually, it
            # HEADER: is definitely not recommended.
            127.0.0.1       localhost
            127.0.1.1       teste01

            # The following lines are desirable for IPv6 capable hosts
            ::1     localhost       ip6-localhost ip6-loopback
            ::1     localhost6.localdomain6 localhost6
            fe00::0 ip6-localnet
            ff02::1 ip6-allnodes
            ff02::2 ip6-allrouters
            ff02::3 ip6-allhosts

            # Criado pelo puppet
            10.10.10.01     teste1.fcn.edu.br       # Adicionado via puppet
            20.20.20.02     teste2.fcn.edu.br       # Adicionado pelo puppet



